import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./context/ThemeContext";
import { AudioProvider } from "./context/AudioContext";
import I18nProvider from "./context/I18nProvider";
import Layout from "./components/Layout";
import "./globals.css";
import "nes.css/css/nes.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProvider>
          <ThemeProvider>
            <AudioProvider>
              <main>
                <Layout>
                  {children}
                </Layout>
              </main>
            </AudioProvider>
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
